CREATE TABLE `INVENTORY_LOCK` (
  `PRODUCT_ID` int(11) NOT NULL,
  `ORDER_ID` int(11) NOT NULL,
  `QUANTITY` int(50),
  `EXPIRE_DATE` datetime,
  `CREATION_DATE` datetime,
  `UPDATE_DATE` datetime,
  PRIMARY KEY (`PRODUCT_ID`, `ORDER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;