CREATE TABLE `INVENTORY_LOCK` (
  `PROEDUCT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ORDER_ID` int(11) DEFAULT NULL,
  `QUANTITY` int(50) DEFAULT NULL,
  `EXPIRE_DATE` datetime(11) DEFAULT NULL,
  `CREATION_DATE` datetime DEFAULT NULL,
  `UPDATE_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`PROEDUCT_ID`, `ORDER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;