CREATE TABLE `COMMERCE_ITEM_DELIVERY` (
	`COMMERCE_ITEM_ID`  int NOT NULL ,
	`CONSIGNOR`  varchar(50) NULL,
	`DELIVERED`  bit(1) NULL ,
	`RECEIVED`  bit(1) NULL ,
	`LOGISTICS`  varchar(50) NULL ,
	`DELIVERY_TIME`  datetime NULL ,
	`TRACKING_NO`  varchar(20) NULL ,
	PRIMARY KEY (`COMMERCE_ITEM_ID`)
);