 UPDATE CATEGORIES  SET DESCRIPTION ='品真 质纯 艺臻' WHERE CATEGORY_ID=43;

 UPDATE CATEGORIES  SET DESCRIPTION ='品真 质纯 艺臻' WHERE CATEGORY_ID=49;

 UPDATE CATEGORIES  SET DESCRIPTION ='品真 质纯 艺臻' WHERE CATEGORY_ID=52;

 UPDATE CATEGORIES  SET DESCRIPTION ='品真 质纯 艺臻' WHERE CATEGORY_ID=56;
