ALTER TABLE `ORDER`
MODIFY COLUMN `USER_ID`  varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL AFTER `ORDER_ID`,
MODIFY COLUMN `STATUS`  int(11) NOT NULL COMMENT '1=INITAL\n2=COMPLETE\n3=PAY\n4=NO_PENDING_ACTION' AFTER `USER_ID`,
ADD COLUMN `ORDER_TYPE`  int(11) NULL DEFAULT 1 COMMENT '1=B2C ORDER\r\n2=P2P ORDER' AFTER `EASY_BUY`;
UPDATE `ORDER` SET ORDER_TYPE = 1;