CREATE TABLE `PAGE_BACKGROUND` (
  `PAGE_BACKGROUND_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CREATION_DATE` datetime DEFAULT NULL,
  `UPDATE_DATE` datetime DEFAULT NULL,
  `START_DATE` datetime DEFAULT NULL,
  `END_DATE`  datetime DEFAULT NULL,
  PRIMARY KEY (`PAGE_BACKGROUND_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
