CREATE TABLE `TOKEN` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TOKEN_NUMBER` varchar(200) DEFAULT NULL,
  `USERNAME` varchar(45) DEFAULT NULL,
  `PHONE_ID` varchar(200) DEFAULT NULL,
  `CREATE_DATE` datetime DEFAULT NULL,
  `OUT_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;
