ALTER TABLE `mp`.`TENDER` 
ADD COLUMN `IMAGE_DESC` VARCHAR(45) NULL ;

ALTER TABLE `mp`.`PRODUCT`
ADD COLUMN `IMAGE_DESC` VARCHAR(45) NULL ;

ALTER TABLE `mp`.`CATEGORIES`
ADD COLUMN `IMAGE_DESC` VARCHAR(45) NULL ;


