CREATE TABLE `RECOMMENDED_PRODUCT` (
	`RECOMMENDED_PRODUCT_ID`  int NOT NULL AUTO_INCREMENT,
	`NAME`  varchar(50) NULL,
	`PRODUCT_TYPE`  varchar(10) NULL ,
	`SORT`  int NULL ,
	`URL`  varchar(150) NULL ,
	`MEDIA_ID` int NULL,
	PRIMARY KEY (`RECOMMENDED_PRODUCT_ID`)
);