ALTER TABLE `mp`.`P2P_INFO`
ADD COLUMN `HANDLING_FEE` decimal(10,2) NULL ,
ADD COLUMN `INTEREST_RATE` decimal(10,2) NULL ,
ADD COLUMN `HANDLING_RATE` decimal(10,2) NULL ,
ADD COLUMN `PAY_TIME` datetime NULL ,
ADD COLUMN `CREATION_DATE` datetime NULL ,
ADD COLUMN `UPDATE_DATE` datetime NULL ,
CHANGE COLUMN `EXPECT_INCOMING` `EXPECT_INCOMING` decimal(10,2) NULL,
CHANGE COLUMN `ACTUAL_INCOMING` `ACTUAL_INCOMING` decimal(10,2) NULL;
