CREATE TABLE `THIRD_LOGIN` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `OPEN_ID` varchar(255) DEFAULT NULL,
  `TYPE` varchar(100) DEFAULT NULL,
  `TOKEN` varchar(255) DEFAULT NULL,
  `USER_ID` int(11) DEFAULT NULL,
  `EXPIRE` datetime DEFAULT NULL,
  `REFRESH_TOKEN` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;