UPDATE `ORDER` SET  `TYPE` = 1 WHERE `CREATION_DATE` < NOW();
UPDATE `COMMERCE_ITEM` SET  `TYPE` = 1 WHERE `CREATION_DATE` < NOW();

ALTER TABLE `P2P_INFO` ADD `PLACE_QUANTITY` INT;
ALTER TABLE `P2P_INFO` ADD `UNIT_PRICE` DEICMAL(10,2);

ALTER TABLE `TENDER` ADD `PAWN_OWNER_ID` INT;