
INSERT INTO `CATEGORIES` (CATEGORY_ID,NAME,PARENT_CATEGORY_ID,CODE,STATUS,TYPE,MEDIA_ID) VALUES ('18', '购物与支付', null, '1', null, 'HELP_ROOT',  null);
INSERT INTO `CATEGORIES` (CATEGORY_ID,NAME,PARENT_CATEGORY_ID,CODE,STATUS,TYPE,MEDIA_ID) VALUES ('19', ' 配送说明', null, '1', null, 'HELP_ROOT', null);
INSERT INTO `CATEGORIES` (CATEGORY_ID,NAME,PARENT_CATEGORY_ID,CODE,STATUS,TYPE,MEDIA_ID) VALUES ('20', '关于我们', null, '1', null, 'HELP_ROOT',   null);
INSERT INTO `CATEGORIES` (CATEGORY_ID,NAME,PARENT_CATEGORY_ID,CODE,STATUS,TYPE,MEDIA_ID) VALUES ('21', '售后服务', null, '1', null, 'HELP_ROOT',   null);
INSERT INTO `CATEGORIES` (CATEGORY_ID,NAME,PARENT_CATEGORY_ID,CODE,STATUS,TYPE,MEDIA_ID) VALUES ('22', '会员中心', null, '1', null, 'HELP_ROOT',   null);