
--   对categorie表进行数据添加
INSERT INTO `CATEGORIES` (CATEGORY_ID,NAME,PARENT_CATEGORY_ID,CODE,STATUS,TYPE,MEDIA_ID) VALUES (1, '琥珀', 9, '1', NULL, 'HIERARCHY', 12);
INSERT INTO `CATEGORIES` (CATEGORY_ID,NAME,PARENT_CATEGORY_ID,CODE,STATUS,TYPE,MEDIA_ID) VALUES (2, '蓝宝石', 9, '1', NULL, 'HIERARCHY', 70);
INSERT INTO `CATEGORIES` (CATEGORY_ID,NAME,PARENT_CATEGORY_ID,CODE,STATUS,TYPE,MEDIA_ID) VALUES (3, '红宝石', 9, '1', NULL, 'HIERARCHY', 72);
INSERT INTO `CATEGORIES` (CATEGORY_ID,NAME,PARENT_CATEGORY_ID,CODE,STATUS,TYPE,MEDIA_ID) VALUES (4, '碧玺', 9, '1', NULL, 'HIERARCHY', 84);
INSERT INTO `CATEGORIES` (CATEGORY_ID,NAME,PARENT_CATEGORY_ID,CODE,STATUS,TYPE,MEDIA_ID) VALUES (5, '表', 10, '1', NULL, 'HIERARCHY', 105);
INSERT INTO `CATEGORIES` (CATEGORY_ID,NAME,PARENT_CATEGORY_ID,CODE,STATUS,TYPE,MEDIA_ID) VALUES (6, '翡翠', 9, '1', NULL, 'HIERARCHY', 170);
INSERT INTO `CATEGORIES` (CATEGORY_ID,NAME,PARENT_CATEGORY_ID,CODE,STATUS,TYPE,MEDIA_ID) VALUES (7, '和田玉', 9, '1', NULL, 'HIERARCHY', 260);
INSERT INTO `CATEGORIES` (CATEGORY_ID,NAME,PARENT_CATEGORY_ID,CODE,STATUS,TYPE,MEDIA_ID) VALUES (8, '钻戒', 11, '1', NULL, 'HIERARCHY', 280);
INSERT INTO `CATEGORIES` (CATEGORY_ID,NAME,PARENT_CATEGORY_ID,CODE,STATUS,TYPE,MEDIA_ID) VALUES (9, '珠宝玉石', NULL, '1', NULL, 'ROOT', 60);
INSERT INTO `CATEGORIES` (CATEGORY_ID,NAME,PARENT_CATEGORY_ID,CODE,STATUS,TYPE,MEDIA_ID) VALUES (10, '高级手表', NULL, '1', NULL, 'ROOT', 105);
INSERT INTO `CATEGORIES` (CATEGORY_ID,NAME,PARENT_CATEGORY_ID,CODE,STATUS,TYPE,MEDIA_ID) VALUES (11, '戒指饰品', NULL, '1', NULL, 'ROOT', 280);

INSERT INTO `CATEGORIES` (CATEGORY_ID,NAME,PARENT_CATEGORY_ID,CODE,STATUS,TYPE,MEDIA_ID) VALUES (12, '黄铂金', NULL, '1', NULL, 'ROOT', 290);
INSERT INTO `CATEGORIES` (CATEGORY_ID,NAME,PARENT_CATEGORY_ID,CODE,STATUS,TYPE,MEDIA_ID) VALUES (13, '千足金', 12, '1', NULL, 'HIERARCHY', 307);
INSERT INTO `CATEGORIES` (CATEGORY_ID,NAME,PARENT_CATEGORY_ID,CODE,STATUS,TYPE,MEDIA_ID) VALUES (14, '沉香木', 15, '1', NULL, 'HIERARCHY', 306);
INSERT INTO `CATEGORIES` (CATEGORY_ID,NAME,PARENT_CATEGORY_ID,CODE,STATUS,TYPE,MEDIA_ID) VALUES (15, '木制品', NULL, '1', NULL, 'ROOT', 306);
INSERT INTO `CATEGORIES` (CATEGORY_ID,NAME,PARENT_CATEGORY_ID,CODE,STATUS,TYPE,MEDIA_ID) VALUES (16, '奢侈品', NULL, '1', NULL, 'ROOT', 323);
INSERT INTO `CATEGORIES` (CATEGORY_ID,NAME,PARENT_CATEGORY_ID,CODE,STATUS,TYPE,MEDIA_ID) VALUES (17, ' 卡地亚', 16, '1', NULL, 'HIERARCHY', 325);


INSERT INTO `CATEGORIES`  (CATEGORY_ID,NAME,CODE,TYPE)  VALUES 
(18, ' 交易管理', 1 ,  'HELP_ROOT'),
 (19, ' 收藏夹', 1 ,  'HELP_ROOT'),
 (20, ' 讨论咨询',1,  'HELP_ROOT'),
 (21, ' 个人中心', 1 , 'HELP_ROOT'),
 (22, ' 帮助中心', 1 ,  'HELP_ROOT');
