ALTER TABLE `PRODUCT` ADD `TITLE` VARCHAR(200);
ALTER TABLE `PRODUCT` ADD `SHORT_DESCRIPYION` VARCHAR(200);
ALTER TABLE `PRODUCT` ADD `IS_NEW` VARCHAR(50);

UPDATE `PRODUCT` SET IS_NEW='95成 未成使用过,全新!',TITLE ='天王表经典桥系列，蓝宝石玻璃镜面，时尚机械手表。',SHORT_DESCRIPYION= '宝石蓝 斜阳红 翡翠绿 琥珀黄 高级灰' WHERE 1=1;