CREATE TABLE `SHIPPING_INFO` (
  `SHIPPING_INFO_ID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `USER_ID` int(11) NOT NULL COMMENT '',
  `NAME` VARCHAR(100) NOT NULL COMMENT '',
  `PHONE` VARCHAR(45) NULL COMMENT '',
  `TELEPHONE` VARCHAR(45) NULL COMMENT '',
  `PROVINCE` VARCHAR(45) NULL COMMENT '',
  `CITY` VARCHAR(45) NULL COMMENT '',
  `DISTRICT` VARCHAR(45) NULL COMMENT '',
  `ADDRESS` VARCHAR(200) NULL COMMENT '',
  `EMAIL` VARCHAR(200) NULL COMMENT '',
  `STATUS` INT NULL COMMENT '0=INVALID\n1=AVAILABLE',
  `PRIMARAY` TINYINT(1) DEFAULT 0 COMMENT '',
  `CREATION_DATE` DATETIME NULL COMMENT '',
  `UPDATE_DATE` DATETIME NULL COMMENT '',
  PRIMARY KEY (`SHIPPING_INFO_ID`)  COMMENT '')
  ENGINE = InnoDB;
  
  ALTER TABLE `SHIPPING_ADDRESS` ADD `TELEPHONE` VARCHAR(45);
  ALTER TABLE `SHIPPING_ADDRESS` ADD `EMAIL` VARCHAR(200);