ALTER TABLE `SHIPPING_INFO` DROP `PRIMARAY`;
ALTER TABLE `USERS` ADD `DEFAULT_ADDRESS_ID` INT;
ALTER TABLE `SHIPPING` ADD `SHIPPING_TYPE` VARCHAR(20);
ALTER TABLE `SHIPPING_METHOD` ADD `LOCATION_ID` INT;
ALTER TABLE `SHIPPING_METHOD` ADD `PHONE` VARCHAR(45);
ALTER TABLE `ORDER` ADD `SHIPPING_ID` INT;