ALTER TABLE `PAYMENT_GROUP` ADD `TRACKING_NO` VARCHAR(200);
ALTER TABLE `PAYMENT_GROUP` ADD `UPDATE_DATE` DATETIME;
ALTER TABLE `TRANSACTIONS` ADD `ORDER_ID` INT;
ALTER TABLE `TRANSACTIONS` CHANGE `PAYMENT_GROUP_ID` `PAYMENT_GROUP_ID` INT;