CREATE TABLE IF NOT EXISTS `RECENT_BROWSE` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `USER_ID` INT NOT NULL COMMENT '',
  `PROD_ID` INT NOT NULL COMMENT '',
  `CREATION_DATE` DATETIME NOT NULL COMMENT '',
  `UPDATE_DATE` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`ID`)  COMMENT '')
ENGINE = InnoDB
