CREATE TABLE `HOT_SEARCH` (
  `HOT_SEARCH_ID` int(11) NOT NULL DEFAULT '0',
  `TERM` varchar(45) DEFAULT NULL,
  `MEDIA_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`HOT_SEARCH_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `HOT_SEARCH` VALUES ('1', '商品', '1');
INSERT INTO `HOT_SEARCH` VALUES ('2', '物品', '2');
INSERT INTO `HOT_SEARCH` VALUES ('3', '3', '3');
INSERT INTO `HOT_SEARCH` VALUES ('4', '4', '4');
INSERT INTO `HOT_SEARCH` VALUES ('5', '5', '5');

ALTER TABLE `CATEGORIES` ADD `COLOR` VARCHAR(45);
UPDATE `CATEGORIES` SET COLOR='#006727' WHERE 1=1;


